// <auto-generated />
using System;
using Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(BBBankContext))]
    [Migration("20250221084750_fakeAccounts")]
    partial class fakeAccounts
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entites.Account", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AccountStatus")
                        .HasColumnType("int");

                    b.Property<string>("AccountTitle")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CurrentBalance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            AccountNumber = "0001-1001",
                            AccountStatus = 0,
                            AccountTitle = "Patterns Tech",
                            CurrentBalance = 3500m,
                            UserId = "5b1aa188-636f-436a-a2da-ae742ddadedf"
                        },
                        new
                        {
                            Id = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            AccountNumber = "0002-2002",
                            AccountStatus = 0,
                            AccountTitle = "John Doe",
                            CurrentBalance = 545m,
                            UserId = "52694168-6706-4595-bdea-bae0da5923f0"
                        },
                        new
                        {
                            Id = "447764ed-69b9-4c44-8262-e9575cafccd1",
                            AccountNumber = "3-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 3",
                            CurrentBalance = 300m,
                            UserId = "3"
                        },
                        new
                        {
                            Id = "c74f4cb8-966c-4d38-9076-d3c933b6b0cd",
                            AccountNumber = "4-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 4",
                            CurrentBalance = 400m,
                            UserId = "4"
                        },
                        new
                        {
                            Id = "cec07431-c29c-4d7b-9855-4b81f4956b78",
                            AccountNumber = "5-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 5",
                            CurrentBalance = 500m,
                            UserId = "5"
                        },
                        new
                        {
                            Id = "9339a982-d23c-4728-b883-4a3a7b733611",
                            AccountNumber = "6-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 6",
                            CurrentBalance = 600m,
                            UserId = "6"
                        },
                        new
                        {
                            Id = "37688472-c1ab-4ec4-b52f-3a8527d1a771",
                            AccountNumber = "7-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 7",
                            CurrentBalance = 700m,
                            UserId = "7"
                        },
                        new
                        {
                            Id = "08838ac3-add9-4392-bd40-03dab85db89a",
                            AccountNumber = "8-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 8",
                            CurrentBalance = 800m,
                            UserId = "8"
                        },
                        new
                        {
                            Id = "fa32b50a-5cc2-4fb3-a75e-a03db682db12",
                            AccountNumber = "9-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 9",
                            CurrentBalance = 900m,
                            UserId = "9"
                        },
                        new
                        {
                            Id = "4c6982e1-fb17-4cc1-a9ff-921d39ae3228",
                            AccountNumber = "10-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 10",
                            CurrentBalance = 1000m,
                            UserId = "10"
                        },
                        new
                        {
                            Id = "6bc79aed-08fb-4bdf-a2be-88b26c3a4429",
                            AccountNumber = "11-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 11",
                            CurrentBalance = 1100m,
                            UserId = "11"
                        },
                        new
                        {
                            Id = "c14816d9-2238-44ea-a6a3-7f826895d601",
                            AccountNumber = "12-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 12",
                            CurrentBalance = 1200m,
                            UserId = "12"
                        },
                        new
                        {
                            Id = "ffb7d932-e1af-4bfc-9dd2-2037ac668822",
                            AccountNumber = "13-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 13",
                            CurrentBalance = 1300m,
                            UserId = "13"
                        },
                        new
                        {
                            Id = "2b55ef13-6c92-415b-851e-d91ce819210b",
                            AccountNumber = "14-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 14",
                            CurrentBalance = 1400m,
                            UserId = "14"
                        },
                        new
                        {
                            Id = "69c8ab81-f5e9-4598-aecc-0948c17f3601",
                            AccountNumber = "15-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 15",
                            CurrentBalance = 1500m,
                            UserId = "15"
                        },
                        new
                        {
                            Id = "d26ffa0f-95c3-45bc-8907-4429ff68451d",
                            AccountNumber = "16-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 16",
                            CurrentBalance = 1600m,
                            UserId = "16"
                        },
                        new
                        {
                            Id = "471b9643-4801-4b43-a50b-487b621d9b3c",
                            AccountNumber = "17-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 17",
                            CurrentBalance = 1700m,
                            UserId = "17"
                        },
                        new
                        {
                            Id = "f311a7f9-8467-41eb-a237-db7473e7b3fb",
                            AccountNumber = "18-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 18",
                            CurrentBalance = 1800m,
                            UserId = "18"
                        },
                        new
                        {
                            Id = "610356ec-2bba-462e-8fa9-2984a004fdc2",
                            AccountNumber = "19-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 19",
                            CurrentBalance = 1900m,
                            UserId = "19"
                        },
                        new
                        {
                            Id = "ff6af9be-9145-4165-ab7e-6a8b3066b6cf",
                            AccountNumber = "20-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 20",
                            CurrentBalance = 2000m,
                            UserId = "20"
                        },
                        new
                        {
                            Id = "235b840a-5adb-4bb0-b772-68e36b63692f",
                            AccountNumber = "21-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 21",
                            CurrentBalance = 2100m,
                            UserId = "21"
                        },
                        new
                        {
                            Id = "9fd1b484-456c-46b6-8ca3-f70e6717f31b",
                            AccountNumber = "22-xxx-xxx",
                            AccountStatus = 1,
                            AccountTitle = "Fake Account 22",
                            CurrentBalance = 2200m,
                            UserId = "22"
                        });
                });

            modelBuilder.Entity("Entites.Transaction", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("TransactionAmount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("TransactionDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = "958db5f3-0f02-4c7d-bc31-e2296e25344c",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = 3000m,
                            TransactionDate = new DateTime(2025, 2, 20, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(5561),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "be46c1e2-75a2-41e5-82f3-5bc5f5407a88",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = -500m,
                            TransactionDate = new DateTime(2024, 2, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(6955),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "c0f382fb-d94d-4eed-bdbf-80fa296622d2",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = 1000m,
                            TransactionDate = new DateTime(2023, 2, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7032),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "865c10a7-68fc-4a8d-a55f-5101bf1be801",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = 500m,
                            TransactionDate = new DateTime(2024, 11, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7040),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "a0d86a11-ef32-44b7-86b1-402ad7463fb1",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = -200m,
                            TransactionDate = new DateTime(2024, 10, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7102),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "15fae58c-7507-4b34-989c-79ab7cbb4e78",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = 500m,
                            TransactionDate = new DateTime(2024, 9, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7110),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "94e179db-784b-4188-bc88-4252e85a132d",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = 200m,
                            TransactionDate = new DateTime(2024, 8, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7134),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "4faa9d52-eec3-4eab-b631-d05a39be331f",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = -300m,
                            TransactionDate = new DateTime(2024, 7, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7141),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "17f6797a-f486-4414-87fe-8ba8b9aef4b2",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = -100m,
                            TransactionDate = new DateTime(2024, 6, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7155),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "e53b04a4-df36-4209-9285-8db630992f20",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = 200m,
                            TransactionDate = new DateTime(2024, 5, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7212),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "2d90c76e-1912-4ef2-80a5-d610831a5b05",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = -500m,
                            TransactionDate = new DateTime(2024, 4, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7229),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "03387228-a5b1-4915-9af6-d273d62f5eed",
                            AccountId = "37846734-172e-4149-8cec-6f43d1eb3f60",
                            TransactionAmount = 900m,
                            TransactionDate = new DateTime(2024, 3, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7236),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "256a4940-f2d6-42c0-9306-d2c7975a2aad",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = 2000m,
                            TransactionDate = new DateTime(2025, 2, 20, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7249),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "036267d0-6f41-46b7-9dce-bd2f56b97dc5",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = -400m,
                            TransactionDate = new DateTime(2024, 2, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7257),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "fca4b8f0-1d5a-43da-8536-d9f5bbcc8a24",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = 9000m,
                            TransactionDate = new DateTime(2023, 2, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7271),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "1bfb3a57-33fd-4724-96e8-066530ee9976",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = 200m,
                            TransactionDate = new DateTime(2024, 11, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7292),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "a200069f-336a-42ca-b564-617c9553681c",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = -100m,
                            TransactionDate = new DateTime(2024, 10, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7298),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "e21aced0-d75c-4aec-9a2d-4b6c6a67e302",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = 300m,
                            TransactionDate = new DateTime(2024, 9, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7306),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "e7611ca6-389f-4d2d-b010-11572a585d4e",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = 100m,
                            TransactionDate = new DateTime(2024, 8, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7313),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "9a4e5783-fc28-4ee4-8ce7-a903ded088d2",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = -200m,
                            TransactionDate = new DateTime(2024, 7, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7320),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "3f3e7eca-2bce-4272-982c-b2d3640d98c8",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = -200m,
                            TransactionDate = new DateTime(2024, 6, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7330),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "6f836b03-c618-4785-bdd3-123688b83ec7",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = 300m,
                            TransactionDate = new DateTime(2024, 5, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7338),
                            TransactionType = 0
                        },
                        new
                        {
                            Id = "af29038e-fa1d-4436-8df9-ba7bd4c9ea30",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = -200m,
                            TransactionDate = new DateTime(2024, 4, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7345),
                            TransactionType = 1
                        },
                        new
                        {
                            Id = "c5702440-8aa7-4b80-b1cf-f60e0ccb52d1",
                            AccountId = "2f115781-c0d2-4f98-a70b-0bc4ed01d780",
                            TransactionAmount = 800m,
                            TransactionDate = new DateTime(2024, 3, 21, 2, 47, 50, 65, DateTimeKind.Local).AddTicks(7351),
                            TransactionType = 0
                        });
                });

            modelBuilder.Entity("Entites.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProfilePicUrl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = "5b1aa188-636f-436a-a2da-ae742ddadedf",
                            Email = "admin@patternstech.com",
                            FirstName = "Patterns",
                            LastName = "Tech",
                            ProfilePicUrl = "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_crop,g_face,r_max/w_200/lady.jpg"
                        },
                        new
                        {
                            Id = "52694168-6706-4595-bdea-bae0da5923f0",
                            Email = "john.doe.ddd@outlook.com",
                            FirstName = "John",
                            LastName = "Doe",
                            ProfilePicUrl = "https://res.cloudinary.com/demo/image/upload/w_400,h_400,c_crop,g_face,r_max/w_200/lady.jpg"
                        },
                        new
                        {
                            Id = "3",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "3998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "4",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "4998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "5",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "5998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "6",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "6998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "7",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "7998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "8",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "8998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "9",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "9998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "10",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "10998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "11",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "11998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "12",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "12998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "13",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "13998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "14",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "14998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "15",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "15998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "16",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "16998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "17",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "17998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "18",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "18998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "19",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "19998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "20",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "20998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "21",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "21998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        },
                        new
                        {
                            Id = "22",
                            Email = "fake@fake.com",
                            FirstName = "Fake",
                            LastName = "Fake",
                            PhoneNumber = "22998877665",
                            ProfilePicUrl = "https://images.freeimages.com/images/premium/previews/1670/16703169-disgusted-lounge-singer.jpg"
                        });
                });

            modelBuilder.Entity("Entites.Account", b =>
                {
                    b.HasOne("Entites.User", "User")
                        .WithOne("Account")
                        .HasForeignKey("Entites.Account", "UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Entites.Transaction", b =>
                {
                    b.HasOne("Entites.Account", "Account")
                        .WithMany("Transactions")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("Entites.Account", b =>
                {
                    b.Navigation("Transactions");
                });

            modelBuilder.Entity("Entites.User", b =>
                {
                    b.Navigation("Account")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
